### ISSUE TITLE
[FE/BE] Change first landing page to LOGGED OUT rather than LOGGED IN

### ISSUE THREAD

**Issue by shafaatUML** [bryanmontalvan/trainboard#10]
Profile on navbar is currently set to signed in, change to sign out when implementing backend user auth. 
![image](https://user-images.githubusercontent.com/113412193/227792246-9fb4e3c2-5775-4723-9f42-87b82068a276.png)

**Comment by bryanmontalvan** [comment]
Completed with PR #19
