### ISSUE TITLE
[BE] Route "Sign Up" button from sign up page to the logged in dashboard page

### ISSUE THREAD

**Issue by shafaatUML** [bryanmontalvan/trainboard#13]
Sign Up button currently does not do anything, route it to the main part of the app so the user is logged in once they sign up. Also add password match confirmation to the Sign Up form itself.
![image](https://user-images.githubusercontent.com/113412193/227795974-57c89224-fbc3-4120-900f-59c0cc82084f.png)

**Comment by bryanmontalvan** [comment]
Completed with PR #19
