### ISSUE TITLE
Setup Firestore to store user workouts

### ISSUE THREAD

**Issue by bryanmontalvan** [bryanmontalvan/trainboard#6]
## Description:

We will need to setup a primary database to store user created workouts. Thankfully using the Firebase suite we are able to easily data by user account (synergy between Firebase Auth & Firestore).

This functionality will require not only setting up Firestore but also figuring out the best data-structure to parse, modify, and store on client. 

## Steps:
- Create a Firestore instance on the Firebase console 
- Install Firestore on the project (if not done already)
- Use built-in methods to store data
- Create a data-structure which will work best with the workout data
- Test functionality, make sure to test and handle multiple writes to the database. (Meaning user errors, security measures will be done when we get closer to the production release data).

## Features by completion:

- [x] Create data-structure to store workouts (diagram to be shared soon)
- [x] Implement workout-creator, meaning to allow users to create workouts by using the workout creator table
- [x] Display user created workouts on /dashboard and workout related pages
- [x] Allow users to view the specific view of individual workouts (dynamic routing & components)
- [x] Allow users to delete a workout
- [x] Allow users to modify their workout

(Note: These features are bare-boned, refining is required afterwards)
## Future features

- Implement ordering of workouts via WorkoutDropdown
- Implement Favorite fuctionality

## Resources:
- [Firebase Firestore Documentation](https://firebase.google.com/docs/firestore)

**Comment by banstack** [comment]
#59 

Last PR pertaining merged for the CRUD functionality
